### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no J3D in java.library.path

### ISSUE THREAD

**Issue by buffonly** [ChiralBehaviors/Voronoi-3D#2]
when I run main method in class OrientedFaceInspector,have an error 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no J3D in java.library.path

**Comment by buffonly** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no J3D in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at javax.media.j3d.MasterControl$22.run(MasterControl.java:889)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:886)
	at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:229)
	at javax.media.j3d.Canvas3D.<clinit>(Canvas3D.java:3533)
	at com.hellblazer.delaunay.gui.OrientedFaceInspector.<init>(OrientedFaceInspector.java:36)
	at com.hellblazer.delaunay.gui.OrientedFaceInspector.main(OrientedFaceInspector.java:25)

**Comment by buffonly** [comment]
How can I solve this problem,And how can I use this programe

**Comment by Hellblazer** [comment]
somewhat fixed.  moved to java fx
